[package]
name = "adhd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotlars = "0.5.0"
evcxr = "0.17.0"
hashbrown = { version = "0.14", features = ["rayon", "ahash", "serde", "raw"] }
linfa = "0.7.0"
polars = { version = "0.42.0", features = [
    "lazy", 
    "csv", 
] }

