
services:
  server:
    container_name: adhd-analytics-server
    build:
      context: .
      target: final
    ports:
      - '3000:3000'
  
  web:
    container_name: adhd-analytics-web
    build: ./web
    ports:
      - '4200:4200'