# Ripped from here - https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
name: Cargo CI
on:
  push:
    branches: [main]

# TODO: Split apart Back & Frontend Build/Test/Deploy

jobs:
  install_angular_cli:
    name: Install Latest Angular
    uses: actions/angular-github-actions
  
  cargo_build_and_test:
    name: Cargo build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo build --release --all-features
      - run: cargo test

# TODO: Re-enable
#  clippy:
#    name: Clippy
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#      - run: rustup component add clippy
#      - uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: -- -D warnings

